# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/06_calib.steffl.ipynb (unless otherwise specified).

__all__ = ['steffl_spica_dates', 'steffl_spica_nasa_dates']

# Cell
import pandas as pd
from .greg import filter_spica_for_date
from ..pds import CatalogFilter
from planetarypy.utils import iso_to_nasa_date
from ..io import UVPDS, UVISObs

# Cell
steffl_spica_dates = ["2001-04-3", "2002-07-17", "2003-05-19"]
steffl_spica_nasa_dates = [iso_to_nasa_date(i) for i in steffl_spica_dates]
steffl_spica_nasa_dates