package:
  name: pyuvis
  version: 0.6.4
source:
  sha256: 187f4b1a7c9bdbd115678b803c9fed2c3984fc0aec1c15ccd679f537f19e1e13
  url: https://files.pythonhosted.org/packages/f8/a4/47e1874de802fdecb5d5db4772d25dd683b30485870086a634ee8925f660/pyuvis-0.6.4.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python tools for Cassini UVIS data
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas>=1.0
  - xarray>=0.19
  - hvplot>=0.7
  - planetarypy>=0.15
  run:
  - pip
  - python
  - packaging
  - pandas>=1.0
  - xarray>=0.19
  - hvplot>=0.7
  - planetarypy>=0.15
test:
  imports:
  - pyuvis
