package:
  name: pyuvis
  version: 0.6.2
source:
  sha256: ee5a29a6f5babcabc7f859f2e7036e63c54e14ea369f301795db25889063168d
  url: https://files.pythonhosted.org/packages/53/27/a9990316dae0772366250c9a193a791b983b4f2479d73cc21e3790b3f793/pyuvis-0.6.2.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python tools for Cassini UVIS data
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas>=1.0
  - xarray>=0.19
  - hvplot>=0.7
  - planetarypy>=0.15
  run:
  - pip
  - python
  - packaging
  - pandas>=1.0
  - xarray>=0.19
  - hvplot>=0.7
  - planetarypy>=0.15
test:
  imports:
  - pyuvis
