# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data": "01_hsp_sensitivity.ipynb",
         "s": "01_hsp_sensitivity.ipynb",
         "sens_df": "01_hsp_sensitivity.ipynb",
         "check_kernels": "02_idlsav.ipynb",
         "swap_cell": "02_idlsav.ipynb",
         "read_idlsav_file": "02_idlsav.ipynb",
         "SavConverter": "02_idlsav.ipynb",
         "hv.config.image_rtol": "03_io.ipynb",
         "PDSReader": "03_io.ipynb",
         "UVPDS": "03_io.ipynb",
         "UVISObs": "03_io.ipynb",
         "UVIS_NetCDF": "03_io.ipynb",
         "HSP": "03_io.ipynb",
         "FUV_CDF": "03_io.ipynb",
         "FUV": "03_io.ipynb",
         "EUV_CDF": "03_io.ipynb"}

modules = ["hsp_sensitivity.py",
           "idlsav.py",
           "io.py"]

doc_url = "https://michaelaye.github.io/pyuvis/"

git_url = "https://github.com/michaelaye/pyuvis/tree/master/"

def custom_doc_links(name): return None
