# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_downloads.ipynb (unless otherwise specified).

__all__ = ['url_template', 'url_root', 'url_name']

# Cell
import requests
from urllib.request import urlretrieve

# Cell
url_template = ("http://pds-rings.seti.org/volumes/COUVIS_0xxx/"
                "COUVIS_0001/index/index.tab")

# Cell
url_root = 'http://pds-rings.seti.org/volumes/COUVIS_0xxx/COUVIS_00'

# Cell
url_name = '/index/index.tab'